server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    server_tokens off;

    root /app/;
    index index.php;

    client_max_body_size 6m;

    error_page 400 /public/views/400.html;
    error_page 403 /public/views/403.html;
    error_page 404 /public/views/404.html;
    error_page 413 /public/views/413.html;
    error_page 500 502 503 504 /public/views/500.html;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}